### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by snreid**
Pivotal Story link: https://www.pivotaltracker.com/story/show/176877627

### CODE REVIEW

**Comment by snreid** [comment]
qaready

**Comment by snreid** [comment]
qaready

**Review by anthonylebrun — APPROVED** [review]

**Comment by snreid** [comment]
qaready

**Comment by snreid** [comment]
qaready

**Comment by snreid** [comment]
qaready

**Comment by snreid** [comment]
qaready

**Comment by snreid** [comment]
qaready

**Review by samusgray — APPROVED** [review]
Test approval. Testing, testing, 1, 2, 3....

**Review by samusgray — APPROVED** [review]
Test

**Comment by snreid** [comment]
qaready

**Review by samusgray — APPROVED** [review]
again

**Pull request closed without merging**
